ARCHS = arm64
TARGET = iphone:clang:latest:14.0

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = YourTweakName   # هنا ضع اسم التويك الخاص بك
YourTweakName_FILES = Tweak.xm
YourTweakName_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk